name: spanenv
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - astroid=2.3.3=py37_0
  - blas=1.0=mkl
  - ca-certificates=2020.1.1=0
  - certifi=2020.4.5.1=py37_0
  - cudatoolkit=10.0.130=0
  - faiss-gpu=1.6.3=py37h1a5d453_0
  - freetype=2.9.1=h8a8886c_1
  - intel-openmp=2020.0=166
  - isort=4.3.21=py37_0
  - jpeg=9b=h024ee3a_2
  - lazy-object-proxy=1.4.3=py37h7b6447c_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_0
  - mccabe=0.6.1=py37_1
  - mkl=2020.0=166
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.0.15=py37ha843d7b_0
  - mkl_random=1.1.0=py37hd6b4f25_0
  - ncurses=6.2=he6710b0_0
  - ninja=1.9.0=py37hfd86e86_0
  - numpy=1.18.1=py37h4f9e942_0
  - numpy-base=1.18.1=py37hde5b4d6_1
  - olefile=0.46=py37_0
  - openssl=1.1.1f=h7b6447c_0
  - pillow=7.0.0=py37hb39fc2d_0
  - pip=20.0.2=py37_1
  - pylint=2.4.4=py37_0
  - python=3.7.7=hcf32534_0_cpython
  - pytorch=1.4.0=py3.7_cuda10.0.130_cudnn7.6.3_0
  - readline=8.0=h7b6447c_0
  - setuptools=46.1.3=py37_0
  - six=1.14.0=py37_0
  - sqlite=3.31.1=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - torchvision=0.5.0=py37_cu100
  - wheel=0.34.2=py37_0
  - wrapt=1.12.1=py37h7b6447c_1
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - boto3==1.12.35
    - botocore==1.15.35
    - chardet==3.0.4
    - click==7.1.1
    - cycler==0.10.0
    - docutils==0.15.2
    - filelock==3.0.12
    - idna==2.9
    - jinja2==2.11.2
    - jmespath==0.9.5
    - joblib==0.14.1
    - jsonlines==1.2.0
    - kiwisolver==1.2.0
    - markupsafe==1.1.1
    - matplotlib==3.2.1
    - nltk==3.5
    - pandas==1.0.3
    - protobuf==3.12.2
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - pytorch-crf==0.7.2
    - pytz==2019.3
    - regex==2020.2.20
    - requests==2.23.0
    - s3transfer==0.3.3
    - sacremoses==0.0.38
    - scikit-learn==0.22.2.post1
    - scipy==1.4.1
    - sentencepiece==0.1.85
    - tensorboardx==2.0
    - tokenizers==0.5.2
    - tqdm==4.45.0
    - transformers==2.7.0
    - urllib3==1.25.8

